title: "Google Prompting Essentials"
description: "A blog about Google Prompting Essentials"
baseurl: ""
url: "https://phuongvo9.github.io/google-prompting-essentials"
author:
  name: Phuong Vo
  email: phuongvo9@github.io
github_username:  phuongvo9
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - _site
  - README.md
  - .gitignore
  - .DS_Store