title: Google Prompting Essentials
description: A collection of technical README blogs using Jekyll
baseurl: ""
url: "https://phuongvo9.github.io"
author:
  name: Phuong Vo
  email: phuongvo9@github.io
github_username:  phuongvo9
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - _site
  - README.md
  - .gitignore
  - .DS_Store